### ISSUE TITLE
Tool support for writing plugins in C#

### ISSUE THREAD

**Issue by WonyoungChoi** [flutter-tizen/flutter-tizen#333]
With the implementation of the C# Platform Channel (#127), the basis for writing plugins with C# has been prepared. However, some changes of `flutter-tizen` are needed to support the C# plugins. 

### Basic Concept
1. New `namespace` key in `pubspec.yaml`
Put `namespace`, `pluginClass` and `fileName` to `pubspec.yaml` of the C# plugin to register it. 
```yaml
flutter:
  plugin:
    platforms:
      tizen:
        namespace: Examples.Hello
        pluginClass: HelloPlugin
        fileName: HelloPlugin.csproj
```

2. Each C# plugin class implements an `Tizen.Flutter.Embedding.IFlutterPlugin` interface. 
```csharp
public interface IFlutterPlugin {
  void OnAttachedToEngine(IFlutterPluginBinding binding);
  void OnDetachedFromEngine();
}
```

3. If a flutter application refer a C# plugin, Add registration code for C# plugins to `GeneratedPluginRegistrant.cs`. 
```csharp
        public static void RegisterPlugins(IPluginRegistry registry)
        {
            DotnetPluginRegistry.Instance.AddPlugin(globall::Examples.Hello.HelloPlugin());
        }
```

4. If a flutter application refer a C# plugin, Add `ProjectReference` for C# plugins to `Runner.csproj.user`.
```csharp
   <ProjectReference Include="....../HelloPlugin.csproj" />
```

### Creating a dotnet plugin
```sh
flutter-tizen create -t plugin --platforms tizen --tizen-language csharp my_plugin
```

### Todo
- [x] Add C# embedding APIs for dotnet plugin registration.
- [x] Add tooling for building dotnet plugins and application using the plugins.
- [x] Add template and fix `create` command for the dotnet plugin template.
- [ ] Documentation for the dotnet plugin.
