### ISSUE TITLE
Creating Tizen.Flutter.Embedding nuget package

### ISSUE THREAD

**Issue by WonyoungChoi** [flutter-tizen/flutter-tizen#343]
Currently, the flutter-tizen application written in C# language refers to the `Tizen.Flutter.Embedding` as a `ProjectReference`. 
This always makes it possible to use the latest `Tizen.Flutter.Embedding` and has the advantage of being easy to test it.
However, for `ProjectReference`, the application must know the installation location of the `flutter-tizen` and additional work must be added to the `flutter-tizen` tool. This causes many complex problems in supporting the `dotnet plugin`.
In addition, the fact that the application behavior can be changed due to the change in the `Tizen.Flutter.Embedding` referenced at each build time may undermine the reliability of the application. 
For these reasons, I would like to create the `Tizen.Flutter.Embedding` nuget package and allow applications and plugins to refer this nuget package.

### With this nuget package, ###
- The application can use a fixed version of `Tizen.Flutter.Embedding` regardless of the `flutter-tizen` version.
- The application does not need to know the installation location of the `flutter-tizen`.
- Additional build targets can be provided in the nuget package.

### XXX.csproj.user file ###
The .user file generated by the `pub get` command will be maintained for the convenience of `Tizen.Flutter.Embedding` tests using `ProjectReference`.

### Todo: ###
- [ ] Setting versioning policy.
- [ ] Creating the nuget package.
- [ ] CI / CD works. 
- [ ] Fix templates of c# application.

**Comment by swift-kim** [comment]
I don't agree with this idea. Back in the day [we were using a similar approach](https://github.com/flutter-tizen/flutter-tizen/pull/103) (`PackageReference`) and we used to inject the `FlutterEmbeddingVersion` value from the tool to csproj:

```xml
  <ItemGroup>
    <PackageReference Include="Tizen.Flutter.Embedding" Version="$(FlutterEmbeddingVersion)*" />
  </ItemGroup>
```

but it made it really hard to test any change in the embedding or keep the `FlutterEmbeddingVersion` value always in sync (it's very easy to forget to update the value). Even if you choose to use a fixed version of the embedding without injecting `FlutterEmbeddingVersion` from the tool, then it becomes more problematic because the value will not generally be updated by the user after the project is created:
- The user should be aware of their project's embedding version and update it manually to use a new feature or apply a bug patch.
- We can't guess which version of the embedding is in use by the user from their error report because `flutter-tizen doctor` will not say about it.

Another small drawback is the increased cost of source-level debugging. Currently, if an app crashes with an unhandled exception during a debug run, it generates a full stack trace of the app's C# code with detailed file path and line number information. We can even attach a Visual Studio debugger to a running app and set breakpoints or evaluate expressions in the embedding. This becomes not generally possible if we choose to use `PackageReference` (even if you publish PDB files along with the nuget package).

**Comment by WonyoungChoi** [comment]
I think it is necessary to fix the `Embedding version` so that users can determine the behavior of their apps. Let's think about the possibility that the use of the latest Embedding, depending on the version of `flutter-tizen`, will affect the builds of existing apps.
And `ProjectReference` can also be used when developing `Embedding` to solve the inconvenience.

Let's talk in more detail offline. 
In the case of `ProjectReference`, I will think more about how to solve the problem of dotnet plugin's embedding reference.

**Comment by swift-kim** [comment]
> Let's think about the possibility that the use of the latest Embedding, depending on the version of `flutter-tizen`, will affect the builds of existing apps.

This is not problem at all. The embedding API is expected to be backward compatible and no breaking change should be made. The Android embedding works in this way too.
