### ISSUE TITLE
Some tasks to be done

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/flutter-tizen#60]
Here are a few general topic issues from my personal TODO list (randomly ordered):

- [x] Document how to utilize HW (rotary) events on watch devices → https://github.com/flutter-tizen/plugins/pull/108
- [x] Apps should rebuild only when necessary (code change, ...) → Partially done: #63, #98
- [x] Check if Flutter apps can be registered on the TV app store
- [x] Analyze app launching-time performance in depth → WIP by @xuelian-bai
- [x] Design a VS Code extension (how to implement: contribution, fork, from scratch, ...) → Addressed by #88
- [ ] Document how to use Firebase in Tizen apps
- [ ] A guide to OAuth 2.0 authentication and authorization in Tizen apps
- [x] A guide to writing app UI for small and non-square (watch) devices → Partially done
- [x] Investigate why I need to click back button twice to quit 2d-inc apps ([example](https://github.com/2d-inc/HistoryOfEverything)) on Tizen devices → #183
- [ ] Articles on flutter-tizen (showcase, internal architecture and etc.)
- [x] Test if DevTools debugger's variable inspection works
- [x] Document how to set up IoT devices (rpi) → #112
- [x] Plugin-related tasks
  - [x] Estimate the amount of work to be done to enable C#-based plugins → #127
  - [x] Migrate plugins to null safety
  - [x] Implement new plugins (candidates: in_app_purchase, lottie, ...) → Maybe later
  - [x] Document limitations of ffi-based plugins → Addressed by https://github.com/flutter-tizen/plugins/issues/123
  - [x] Document how to create a new plugin from scratch → #133

If interested, you can create a dedicated issue for each and assign yourself. Please let me know if you need any details.

**Comment by HidenoriMatsubayashi** [comment]
Great tasks! I'm quite interested in flutter-tizen. Actually, we've been developing [flutter-embedded-linux](https://github.com/sony/flutter-embedded-linux) for Flutter use in embedded Linux, and we are going to create a tool for this embedder to build and run Flutter apps such as `flutter run -d linux-embedded`. Allow me to use this approach as a reference in our tasks. Thank you in advance.

**Comment by swift-kim** [comment]
@HidenoriMatsubayashi Hi. I actually knew about the project since you open sourced it and I was really impressed by your work! 
I know that you eventually want your embedder (and maybe the tool as well) to be merged to the official flutter repo, and if so, another option for you is to fork the flutter repo itself. In our approach, as you might know, we cannot modify the flutter_tools code itself so we had to use many workarounds which introduced extra complexity to implement even simple things, although the commit history looks "cleaner" in return. Anyway, I don't mind whichever approach you choose, and I look forward to seeing good tooling for your beautiful embedders!

**Comment by HidenoriMatsubayashi** [comment]
Thank you for your comment!
